# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-techspike-customer-registry-event:
    build:
      target: development
    image: ffc-techspike-customer-registry-event-development
    container_name: ffc-techspike-customer-registry-event-development
    ports:
      - "4003:3000"
      - "9233:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
