environment: development
name: ffc-techspike-customer-registry-event
namespace: ffc-techspike
workstream: ffc-techspike
image: ffc-techspike-customer-registry-event

labels: {}

appInsights:
  key:

containerConfigMap:
  name: ffc-techspike-customer-registry-event-config-map

containerSecret:
  name: ffc-techspike-customer-registry-event-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0

container:
  eventRequestQueueAddress: ffc-techspike-customer-registry-event
  messageQueueHost: namespace.servicebus.windows.net
  imagePullPolicy: IfNotPresent
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 40Mi
  limitCpu: 40m
  port: 3000

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
